Open311_ServiceType:
  required:
    - id
    - type
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: >-
    As per Open311 an entity of type ServiceType is an acceptable 311 service
    request type. A request type can be unique to the city/jurisdiction.
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Relationship
        model: https://schema.org/URL  
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
